server:
  port: 8080

spring:
  # MVP 개발용 H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  # H2 Console 활성화 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # Redis 설정 (현재는 비활성화, 추후 적용)
  # redis:
  #   host: localhost
  #   port: 6379

# JWT 설정
jwt:
  secret: bXlTZWNyZXRLZXlGb3JOb3RpY2VCb2FyZFByb2plY3RWZXJ5TG9uZ1NlY3JldEtleTEyMzQ1Njc4OQ==
  expiration: 3600000 # 1시간 (밀리초)
  refresh-expiration: 604800000 # 7일 (밀리초)

# 로깅 설정 (개발용)
logging:
  level:
    org.springframework.security: DEBUG
    com.notice_board: DEBUG
